apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 753629740474.dkr.ecr.ap-northeast-2.amazonaws.com/groomi-web
  newName: 753629740474.dkr.ecr.ap-northeast-2.amazonaws.com/groomi-web
  newTag: 65d1a50e
resources:
- ../../base
patchesStrategicMerge:
- deploy-patch.yaml
- service-patch.yaml
