---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: eks-demo
  region: ap-northeast-2        # ap-northeast-2
fargateProfiles:
  - name: goormi-fargate-profile
    selectors:
      - namespace: default
        labels:
          app: goormi-fargate
